### PR TITLE
Vep

### PR DESCRIPTION
**Pull request by Lucpen**
## PR checklist

- [x] Updated Vep
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/genomic-medicine-sweden/tomte/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by Lucpen** [comment]
@nf-core-bot fix linting pretty please

**Comment by Lucpen** [comment]
@nf-core-bot fix linting pretty please

**Comment by Lucpen** [comment]
@nf-core-bot fix linting

**Comment by Lucpen** [comment]
There is a issue with prettier, it is a [known issue](https://nfcore.slack.com/archives/CE6PELWR4/p1705482353145949) and it might be easier to let it be and it will be fixed with the next tools update

**Review by jemten — APPROVED** [review]
Looks good

**Pull request merged**
